<a href="https://colab.research.google.com/github/pavankumarb26/Eamcet-College-Predicter/blob/main/AP_EAMCET_College_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

file_path = "/content/APEAMCET2024LASTRANKDETAILSNONSW.XLS"

In [4]:


df = pd.read_excel(file_path, header=1)

print(df.shape)

(1568, 31)

In [5]:
for i, col in enumerate(df.columns):
    print(i, "->", col)

0 -> SNO
1 -> INSTCODE
2 -> NAME OF THE INSTITUTION
3 -> TYPE
4 -> INST_REG
5 -> DIST
6 -> PLACE
7 -> COED
8 -> AFFL.
9 -> ESTD
10 -> A_REG
11 -> branch_code
12 -> OC_BOYS
13 -> OC_GIRLS
14 -> SC_BOYS
15 -> SC_GIRLS
16 -> ST_BOYS
17 -> ST_GIRLS
18 -> BCA_BOYS
19 -> BCA_GIRLS
20 -> BCB_BOYS
21 -> BCB_GIRLS
22 -> BCC_BOYS
23 -> BCC_GIRLS
24 -> BCD_BOYS
25 -> BCD_GIRLS
26 -> BCE_BOYS
27 -> BCE_GIRLS
28 -> OC_EWS_BOYS
29 -> OC_EWS_GIRLS
30 -> COLLFEE

In [6]:
print(df.dtypes)

SNO                        float64
INSTCODE                    object
NAME OF THE INSTITUTION     object
TYPE                        object
INST_REG                    object
DIST                        object
PLACE                       object
COED                        object
AFFL.                       object
ESTD                       float64
A_REG                       object
branch_code                 object
OC_BOYS                     object
OC_GIRLS                    object
SC_BOYS                     object
SC_GIRLS                    object
ST_BOYS                     object
ST_GIRLS                    object
BCA_BOYS                    object
BCA_GIRLS                   object
BCB_BOYS                    object
BCB_GIRLS                   object
BCC_BOYS                    object
BCC_GIRLS                   object
BCD_BOYS                    object
BCD_GIRLS                   object
BCE_BOYS                    object
BCE_GIRLS                   object
OC_EWS_BOYS                 object
OC_EWS_GIRLS                object
COLLFEE                     object
dtype: object

In [7]:
import os

print(os.listdir("/content"))

['.config', 'APEAMCET2024LASTRANKDETAILSNONSW.XLS', 'sample_data']

In [8]:
print(df.isnull().sum())

SNO                        3
INSTCODE                   1
NAME OF THE INSTITUTION    3
TYPE                       3
INST_REG                   3
DIST                       3
PLACE                      3
COED                       3
AFFL.                      3
ESTD                       3
A_REG                      3
branch_code                3
OC_BOYS                    3
OC_GIRLS                   3
SC_BOYS                    3
SC_GIRLS                   3
ST_BOYS                    3
ST_GIRLS                   3
BCA_BOYS                   3
BCA_GIRLS                  3
BCB_BOYS                   3
BCB_GIRLS                  3
BCC_BOYS                   3
BCC_GIRLS                  3
BCD_BOYS                   3
BCD_GIRLS                  3
BCE_BOYS                   3
BCE_GIRLS                  3
OC_EWS_BOYS                3
OC_EWS_GIRLS               3
COLLFEE                    3
dtype: int64

In [9]:
missing_rows = df[df.isnull().all(axis=1)]
print(missing_rows)

      SNO INSTCODE NAME OF THE INSTITUTION TYPE INST_REG DIST PLACE COED  \
1565  NaN      NaN                     NaN  NaN      NaN  NaN   NaN  NaN

     AFFL.  ESTD  ... BCB_GIRLS BCC_BOYS BCC_GIRLS BCD_BOYS BCD_GIRLS  \
1565   NaN   NaN  ...       NaN      NaN       NaN      NaN       NaN

     BCE_BOYS BCE_GIRLS OC_EWS_BOYS OC_EWS_GIRLS COLLFEE
1565      NaN       NaN         NaN          NaN     NaN

[1 rows x 31 columns]

In [10]:
rows_with_missing = df[df.isnull().any(axis=1)]

print("Rows with at least one missing value:", len(rows_with_missing))
rows_with_missing

Rows with at least one missing value: 3

,SNO,INSTCODE,NAME OF THE INSTITUTION,TYPE,INST_REG,DIST,PLACE,COED,AFFL.,ESTD,...,BCB_GIRLS,BCC_BOYS,BCC_GIRLS,BCD_BOYS,BCD_GIRLS,BCE_BOYS,BCE_GIRLS,OC_EWS_BOYS,OC_EWS_GIRLS,COLLFEE
1565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1566,NaN,Disclaimer:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1567,NaN,1. Last rank statement doesnot reflect the can...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.iloc[1560:1568]

,SNO,INSTCODE,NAME OF THE INSTITUTION,TYPE,INST_REG,DIST,PLACE,COED,AFFL.,ESTD,...,BCB_GIRLS,BCC_BOYS,BCC_GIRLS,BCD_BOYS,BCD_GIRLS,BCE_BOYS,BCE_GIRLS,OC_EWS_BOYS,OC_EWS_GIRLS,COLLFEE
1560,1561.0,CENUPU,CENTURION UNIVERSITY OF TECHNOLOGY & MANAGEMENT,PU,SW,VZM,TEKKALI,COED,CENUPU,2005.0,...,175369,,101069,111913,141351,138267,138267,,,60000
1561,1562.0,CENUPU,CENTURION UNIVERSITY OF TECHNOLOGY & MANAGEMENT,PU,SW,VZM,TEKKALI,COED,CENUPU,2005.0,...,101069,95607,101069,95607,141994,95607,101069,,,
1562,1563.0,CENUPU,CENTURION UNIVERSITY OF TECHNOLOGY & MANAGEMENT,PU,SW,VZM,TEKKALI,COED,CENUPU,2005.0,...,170168,170168,170168,170168,170168,170168,170168,,,60000
1563,1564.0,CENUPU,CENTURION UNIVERSITY OF TECHNOLOGY & MANAGEMENT,PU,SW,VZM,TEKKALI,COED,CENUPU,2005.0,...,143610,143610,143610,143610,143610,143610,143610,,,60000
1564,1565.0,CENUPU,CENTURION UNIVERSITY OF TECHNOLOGY & MANAGEMENT,PU,SW,VZM,TEKKALI,COED,CENUPU,2005.0,...,160598,160598,160598,160598,160598,160598,160598,,,
1565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1566,NaN,Disclaimer:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1567,NaN,1. Last rank statement doesnot reflect the can...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df = df.iloc[:1565].copy()

print(df.shape)
print(df.tail(2))

(1565, 31)
         SNO INSTCODE                          NAME OF THE INSTITUTION TYPE  \
1563  1564.0   CENUPU  CENTURION UNIVERSITY OF TECHNOLOGY & MANAGEMENT   PU
1564  1565.0   CENUPU  CENTURION UNIVERSITY OF TECHNOLOGY & MANAGEMENT   PU

     INST_REG DIST    PLACE  COED   AFFL.    ESTD  ... BCB_GIRLS BCC_BOYS  \
1563       SW  VZM  TEKKALI  COED  CENUPU  2005.0  ...    143610   143610
1564       SW  VZM  TEKKALI  COED  CENUPU  2005.0  ...    160598   160598

     BCC_GIRLS BCD_BOYS BCD_GIRLS BCE_BOYS BCE_GIRLS OC_EWS_BOYS OC_EWS_GIRLS  \
1563    143610   143610    143610   143610    143610
1564    160598   160598    160598   160598    160598

     COLLFEE
1563   60000
1564

[2 rows x 31 columns]

In [13]:
print(df.dtypes)

SNO                        float64
INSTCODE                    object
NAME OF THE INSTITUTION     object
TYPE                        object
INST_REG                    object
DIST                        object
PLACE                       object
COED                        object
AFFL.                       object
ESTD                       float64
A_REG                       object
branch_code                 object
OC_BOYS                     object
OC_GIRLS                    object
SC_BOYS                     object
SC_GIRLS                    object
ST_BOYS                     object
ST_GIRLS                    object
BCA_BOYS                    object
BCA_GIRLS                   object
BCB_BOYS                    object
BCB_GIRLS                   object
BCC_BOYS                    object
BCC_GIRLS                   object
BCD_BOYS                    object
BCD_GIRLS                   object
BCE_BOYS                    object
BCE_GIRLS                   object
OC_EWS_BOYS                 object
OC_EWS_GIRLS                object
COLLFEE                     object
dtype: object

In [14]:
cutoff_cols = df.columns[12:30]

for col in cutoff_cols:
    values = df[col].dropna().astype(str)
    non_numeric = values[~values.str.fullmatch(r"\d+")]

    if len(non_numeric) > 0:
        print(col, "->", non_numeric.unique())

OC_BOYS -> [' ']
OC_GIRLS -> [' ']
SC_BOYS -> [' ']
SC_GIRLS -> [' ']
ST_BOYS -> [' ']
ST_GIRLS -> [' ']
BCA_BOYS -> [' ']
BCA_GIRLS -> [' ']
BCB_BOYS -> [' ']
BCB_GIRLS -> [' ']
BCC_BOYS -> [' ']
BCC_GIRLS -> [' ']
BCD_BOYS -> [' ']
BCD_GIRLS -> [' ']
BCE_BOYS -> [' ']
BCE_GIRLS -> [' ']
OC_EWS_BOYS -> [' ']
OC_EWS_GIRLS -> [' ']

In [15]:
for col in cutoff_cols:
    blank_count = (df[col] == ' ').sum()
    print(f"{col}: {blank_count}")

OC_BOYS: 201
OC_GIRLS: 59
SC_BOYS: 122
SC_GIRLS: 5
ST_BOYS: 146
ST_GIRLS: 22
BCA_BOYS: 138
BCA_GIRLS: 17
BCB_BOYS: 144
BCB_GIRLS: 23
BCC_BOYS: 191
BCC_GIRLS: 94
BCD_BOYS: 142
BCD_GIRLS: 22
BCE_BOYS: 172
BCE_GIRLS: 37
OC_EWS_BOYS: 569
OC_EWS_GIRLS: 561

In [17]:
print(df.iloc[0].to_string())

SNO                                                  1.0
INSTCODE                                            ACEE
NAME OF THE INSTITUTION    ADARSH COLLEGE OF ENGINEERING
TYPE                                                 PVT
INST_REG                                              AU
DIST                                                  EG
PLACE                                         GOLLAPROLU
COED                                                COED
AFFL.                                              JNTUK
ESTD                                              2008.0
A_REG                                                 AU
branch_code                                          CIV
OC_BOYS                                           146103
OC_GIRLS                                          146103
SC_BOYS                                           175237
SC_GIRLS                                          175237
ST_BOYS                                           168197
ST_GIRLS                                          168197
BCA_BOYS                                          146103
BCA_GIRLS                                         146103
BCB_BOYS                                          146103
BCB_GIRLS                                         146103
BCC_BOYS                                          146103
BCC_GIRLS                                         146103
BCD_BOYS                                          146103
BCD_GIRLS                                         146103
BCE_BOYS                                          146103
BCE_GIRLS                                         146103
OC_EWS_BOYS
OC_EWS_GIRLS
COLLFEE                                            43000

In [18]:
print("Unique branch codes:", df["branch_code"].nunique())

print("\nBranch codes:")
print(df["branch_code"].unique())

Unique branch codes: 69

Branch codes:
['CIV' 'CSE' 'ECE' 'EEE' 'MEC' 'CSD' 'CSM' 'INF' 'PHD' 'EIE' 'AIM' 'CAD'
 'AID' 'AGR' 'CAI' 'DS' 'FDE' 'PHM' 'CHE' 'PEE' 'CSC' 'CS' 'CIT' 'AUT'
 'CSG' 'EVT' 'CSB' 'CSO' 'IOT' 'CIC' 'CBA' 'ECA' 'EII' 'ASE' 'CSER' 'MIN'
 'AI' 'BIO' 'GIN' 'IST' 'MET' 'NAM' 'MRB' 'ECM' 'CSS' 'CST' 'ECT' 'CSEB'
 'RBT' 'FDT' 'CCC' 'CIA' 'MMT' 'BDT' 'PET' 'CBC' 'CDA' 'CSW' 'ECES' 'ECV'
 'MAD' 'SWE' 'GDT' 'CN' 'CSBS' 'EBM' 'MAU' 'MII' 'MMM']

In [21]:
branch_counts = df["branch_code"].value_counts()

print(branch_counts)
print("Minimum records for a branch:", branch_counts.min())
print("Maximum records for a branch:", branch_counts.max())

branch_code
CSE     242
ECE     227
EEE     153
MEC     150
CIV     143
       ...
RBT       1
CSEB      1
NAM       1
ECM       1
MII       1
Name: count, Length: 69, dtype: int64
Minimum records for a branch: 1
Maximum records for a branch: 242

In [22]:
college_branch = df.groupby(
    ["INSTCODE", "branch_code"]
).size()

print("Total college-branch combinations:", len(college_branch))
print("Total dataset rows:", len(df))

Total college-branch combinations: 1476
Total dataset rows: 1565

In [23]:
duplicates = college_branch[college_branch > 1]

print("College-branch combinations appearing more than once:",
      len(duplicates))

print(duplicates.head(20))

College-branch combinations appearing more than once: 89
INSTCODE  branch_code
ADTPPU    AGR            2
          AIM            2
          CIV            2
          CSD            2
          CSE            2
          ECE            2
          EEE            2
          INF            2
          MEC            2
          MIN            2
          PET            2
AITSPU    AID            2
          AIM            2
          CAI            2
          CIC            2
          CIV            2
          CSD            2
          CSE            2
          CSM            2
          ECE            2
dtype: int64

In [24]:
df[
    (df["INSTCODE"] == "ADTPPU") &
    (df["branch_code"] == "AGR")
].T

                                       1429                1430
SNO                                  1430.0              1431.0
INSTCODE                             ADTPPU              ADTPPU
NAME OF THE INSTITUTION  ADITYA  UNIVERSITY  ADITYA  UNIVERSITY
TYPE                                     PU                  PU
INST_REG                                 SW                  SW
DIST                                     EG                  EG
PLACE                            SURAMPALEM          SURAMPALEM
COED                                   COED                COED
AFFL.                                ADTPPU              ADTPPU
ESTD                                 2001.0              2001.0
A_REG                                    AU                 SVU
branch_code                             AGR                 AGR
OC_BOYS                              130564              136960
OC_GIRLS                             130564              136960
SC_BOYS                              165388              136960
SC_GIRLS                             165388              136960
ST_BOYS                              140508              136960
ST_GIRLS                             169762              136960
BCA_BOYS                             139359              136960
BCA_GIRLS                            140577              136960
BCB_BOYS                             130564              136960
BCB_GIRLS                            130564              136960
BCC_BOYS                             130564              136960
BCC_GIRLS                            130564              136960
BCD_BOYS                             147857              136960
BCD_GIRLS                            147857              150284
BCE_BOYS                             160847              136960
BCE_GIRLS                            160847              136960
OC_EWS_BOYS
OC_EWS_GIRLS
COLLFEE                               60000

In [25]:
college_branch_region = df.groupby(
    ["INSTCODE", "branch_code", "A_REG"]
).size()

print("Unique college-branch-region combinations:",
      len(college_branch_region))

print("Repeated combinations:",
      (college_branch_region > 1).sum())

Unique college-branch-region combinations: 1565
Repeated combinations: 0

In [26]:
areg_counts = df["A_REG"].value_counts(dropna=False)

print(areg_counts)

A_REG
AU     1049
SVU     516
Name: count, dtype: int64

In [27]:
cutoff_cols = df.columns[12:30]

categories = sorted({
    col.rsplit("_", 1)[0]
    for col in cutoff_cols
})

print("Categories:", categories)
print("Number of categories:", len(categories))

Categories: ['BCA', 'BCB', 'BCC', 'BCD', 'BCE', 'OC', 'OC_EWS', 'SC', 'ST']
Number of categories: 9

In [28]:
genders = sorted({
    col.rsplit("_", 1)[1]
    for col in cutoff_cols
})

print("Genders:", genders)
print("Number of genders:", len(genders))

Genders: ['BOYS', 'GIRLS']
Number of genders: 2

In [29]:
print("COLLFEE dtype:", df["COLLFEE"].dtype)

print("\nMissing values:")
print(df["COLLFEE"].isna().sum())

print("\nUnique sample values:")
print(df["COLLFEE"].unique()[:20])

COLLFEE dtype: object

Missing values:
0

Unique sample values:
[43000 53500 38000 35000 65000 48800 52800 51000 51100 45000 10000 75000
 52400 77800 45700 65800 40000 65600 84900 77500]

In [30]:
non_numeric_fee = df[
    ~df["COLLFEE"].apply(lambda x: str(x).strip().isdigit())
]

print("Non-numeric COLLFEE values:")
print(non_numeric_fee["COLLFEE"].unique())
print("Count:", len(non_numeric_fee))

Non-numeric COLLFEE values:
[' ']
Count: 89

In [31]:
categorical_cols = ["TYPE", "INST_REG", "COED", "AFFL.", "A_REG"]

for col in categorical_cols:
    print(f"\n{col}:")
    print(df[col].value_counts())

TYPE:
TYPE
PVT     1280
PU       167
UNIV      66
SF        50
SS         2
Name: count, dtype: int64

INST_REG:
INST_REG
AU     958
SVU    424
SW     183
Name: count, dtype: int64

COED:
COED
COED     1472
GIRLS      93
Name: count, dtype: int64

AFFL.:
AFFL.
JNTUK     656
JNTUA     401
JNTUV     170
AU         73
ANU        45
VITAPU     30
CENUPU     25
ADTPPU     22
GGURPU     22
AITSPU     22
MBUTPU     20
SRMUPU     10
BESTPU      8
SPMU        8
APUCPU      8
SVU         7
YGVU        6
RSUK        5
SKU         5
AKNU        5
BRAU        5
KSUM        4
ANGRAU      4
SVVU        2
YSRA        2
Name: count, dtype: int64

A_REG:
A_REG
AU     1049
SVU     516
Name: count, dtype: int64

In [32]:
print("ESTD range:")
print(df["ESTD"].min(), "to", df["ESTD"].max())

print("\nCOLLFEE numeric range:")
fee = pd.to_numeric(df["COLLFEE"], errors="coerce")
print(fee.min(), "to", fee.max())

print("\nSNO range:")
print(df["SNO"].min(), "to", df["SNO"].max())

ESTD range:
1926.0 to 2024.0

COLLFEE numeric range:
10000.0 to 160000.0

SNO range:
1.0 to 1565.0

In [33]:
df = df.replace(r'^\s*$', pd.NA, regex=True)

print("Total missing values:", df.isna().sum().sum())

Total missing values: 2754

In [34]:
missing = df.isna().sum()

print(missing[missing > 0].sort_values(ascending=False))

OC_EWS_BOYS     569
OC_EWS_GIRLS    561
OC_BOYS         201
BCC_BOYS        191
BCE_BOYS        172
ST_BOYS         146
BCB_BOYS        144
BCD_BOYS        142
BCA_BOYS        138
SC_BOYS         122
BCC_GIRLS        94
COLLFEE          89
OC_GIRLS         59
BCE_GIRLS        37
BCB_GIRLS        23
ST_GIRLS         22
BCD_GIRLS        22
BCA_GIRLS        17
SC_GIRLS          5
dtype: int64

In [35]:
print(df[df["OC_EWS_BOYS"].isna()].head())

     SNO INSTCODE                 NAME OF THE INSTITUTION TYPE INST_REG DIST  \
0    1.0     ACEE           ADARSH COLLEGE OF ENGINEERING  PVT       AU   EG
3    4.0     ACEE           ADARSH COLLEGE OF ENGINEERING  PVT       AU   EG
19  20.0     APCS                 ADITYA PHARMACY COLLEGE  PVT       AU   EG
41  42.0     CHKN  CHAITANYA INST. OF SCI. AND TECHNOLOGY  PVT       AU   EG
42  43.0     CHKN  CHAITANYA INST. OF SCI. AND TECHNOLOGY  PVT       AU   EG

         PLACE  COED  AFFL.    ESTD  ... BCB_GIRLS BCC_BOYS BCC_GIRLS  \
0   GOLLAPROLU  COED  JNTUK  2008.0  ...    146103   146103    146103
3   GOLLAPROLU  COED  JNTUK  2008.0  ...    150417     <NA>    150417
19  PEDDAPURAM  COED  JNTUK  2004.0  ...    105788    76005    105788
41    KAKINADA  COED  JNTUK  2005.0  ...    145833   142677    142677
42    KAKINADA  COED  JNTUK  2005.0  ...      <NA>     <NA>      <NA>

   BCD_BOYS BCD_GIRLS BCE_BOYS BCE_GIRLS OC_EWS_BOYS OC_EWS_GIRLS COLLFEE
0    146103    146103   146103    146103        <NA>         <NA>   43000
3      <NA>    150417     <NA>    150417        <NA>         <NA>   43000
19    76005    105788    76005    105788        <NA>         <NA>   65000
41   158325    158325   142677    142677        <NA>         <NA>   43000
42   153961    153961     <NA>      <NA>        <NA>         <NA>   43000

[5 rows x 31 columns]

In [36]:
print("Dataset shape:", df.shape)

missing = df.isna().sum()
missing_pct = (missing / len(df)) * 100

print("\nMissing percentage:")
print(missing_pct[missing_pct > 0].sort_values(ascending=False))

Dataset shape: (1565, 31)

Missing percentage:
OC_EWS_BOYS     36.357827
OC_EWS_GIRLS    35.846645
OC_BOYS         12.843450
BCC_BOYS        12.204473
BCE_BOYS        10.990415
ST_BOYS          9.329073
BCB_BOYS         9.201278
BCD_BOYS         9.073482
BCA_BOYS         8.817891
SC_BOYS          7.795527
BCC_GIRLS        6.006390
COLLFEE          5.686901
OC_GIRLS         3.769968
BCE_GIRLS        2.364217
BCB_GIRLS        1.469649
ST_GIRLS         1.405751
BCD_GIRLS        1.405751
BCA_GIRLS        1.086262
SC_GIRLS         0.319489
dtype: float64

In [37]:
print(df.dtypes)

SNO                        float64
INSTCODE                    object
NAME OF THE INSTITUTION     object
TYPE                        object
INST_REG                    object
DIST                        object
PLACE                       object
COED                        object
AFFL.                       object
ESTD                       float64
A_REG                       object
branch_code                 object
OC_BOYS                     object
OC_GIRLS                    object
SC_BOYS                     object
SC_GIRLS                    object
ST_BOYS                     object
ST_GIRLS                    object
BCA_BOYS                    object
BCA_GIRLS                   object
BCB_BOYS                    object
BCB_GIRLS                   object
BCC_BOYS                    object
BCC_GIRLS                   object
BCD_BOYS                    object
BCD_GIRLS                   object
BCE_BOYS                    object
BCE_GIRLS                   object
OC_EWS_BOYS                 object
OC_EWS_GIRLS                object
COLLFEE                     object
dtype: object

In [38]:
for col in df.columns:
    if df[col].dtype == "object":
        print(f"\n{col}:")
        print(df[col].dropna().unique()[:10])

INSTCODE:
['ACEE' 'ACET' 'ACPS' 'ANURSF' 'APCS' 'BVCE' 'BVCR' 'BVTS' 'CHKN' 'GIET']

NAME OF THE INSTITUTION:
['ADARSH COLLEGE OF ENGINEERING'
 'ADITYA COLLEGE OF ENGINEERING AND TECHNOLOGY'
 'ADITYA COLLEGE OF PHARMACY'
 'ADI KAVI NANNAYA UNIVERSITY COLLEGE OF ENGG.-SELF FINANCE'
 'ADITYA PHARMACY COLLEGE' 'B V CHALAMAIAH ENGINEERING COLLEGE'
 'BVC COLLEGE OF ENGINEERING'
 'BONAM VENKATA CHALAMAIAH INST. OF TECH AND SCI.'
 'CHAITANYA INST. OF SCI. AND TECHNOLOGY' 'GIET ENGINEERING COLLEGE']

TYPE:
['PVT' 'SF' 'UNIV' 'SS' 'PU']

INST_REG:
['AU' 'SVU' 'SW']

DIST:
['EG' 'GTR' 'KRI' 'PKS' 'SKL' 'VSP' 'VZM' 'WG' 'ATP' 'CTR']

PLACE:
['GOLLAPROLU' 'PEDDAPURAM' 'RAJAHMUNDRY' 'ODALAREVU' 'AMALAPURAM'
 'KAKINADA' 'JANGAREDDYGUDEM' 'RAMACHANDRAPURAM' 'DIVILI'
 'RAMPACHODAVARAM']

COED:
['COED' 'GIRLS']

AFFL.:
['JNTUK' 'AKNU' 'ANU' 'KSUM' 'JNTUV' 'BRAU' 'AU' 'JNTUA' 'SKU' 'SVU']

A_REG:
['AU' 'SVU']

branch_code:
['CIV' 'CSE' 'ECE' 'EEE' 'MEC' 'CSD' 'CSM' 'INF' 'PHD' 'EIE']

OC_BOYS:
[146103 128861 161894 152545 71458 38871 25298 32023 42426 49158]

OC_GIRLS:
[146103 128861 161894 150417 152545 71458 38871 25298 32023 45361]

SC_BOYS:
[175237 176504 174884 164975 154902 165515 140467 96256 155838 152577]

SC_GIRLS:
[175237 177370 177676 164975 154902 175777 160622 134974 173032 171399]

ST_BOYS:
[168197 157250 161894 152545 108103 151805 162100 151318 172849 162896]

ST_GIRLS:
[168197 157250 161894 150417 157155 121894 156024 162100 165275 172849]

BCA_BOYS:
[146103 161249 161894 152545 121512 71005 52238 62296 90140 99964]

BCA_GIRLS:
[146103 172486 161894 150417 152545 175154 71005 52238 71996 90140]

BCB_BOYS:
[146103 163789 161894 152545 103308 64627 43130 59902 66335 109687]

BCB_GIRLS:
[146103 163789 169552 150417 152545 173293 66698 43130 64713 75200]

BCC_BOYS:
[146103 128861 161894 152545 71458 38871 92163 116275 67761 49158]

BCC_GIRLS:
[146103 128861 161894 150417 152545 121793 38871 103952 116275 99432]

BCD_BOYS:
[146103 176374 161894 156064 96634 49803 36237 50679 61898 83745]

BCD_GIRLS:
[146103 177195 161894 150417 156064 96634 56411 36237 50679 61898]

BCE_BOYS:
[146103 167062 161894 152545 71458 150056 135949 144644 130991 84722]

BCE_GIRLS:
[146103 167062 161894 150417 152545 71458 150056 135949 144644 163207]

OC_EWS_BOYS:
[173286 113560 166550 81009 38653 30016 36444 46455 55707 41596]

OC_EWS_GIRLS:
[136779 118267 81067 41848 28767 35619 46867 55644 40279 128039]

COLLFEE:
[43000 53500 38000 35000 65000 48800 52800 51000 51100 45000]

In [40]:
cutoff_cols = [
    "OC_BOYS", "OC_GIRLS",
    "SC_BOYS", "SC_GIRLS",
    "ST_BOYS", "ST_GIRLS",
    "BCA_BOYS", "BCA_GIRLS",
    "BCB_BOYS", "BCB_GIRLS",
    "BCC_BOYS", "BCC_GIRLS",
    "BCD_BOYS", "BCD_GIRLS",
    "BCE_BOYS", "BCE_GIRLS",
    "OC_EWS_BOYS", "OC_EWS_GIRLS"
]

In [41]:
for col in cutoff_cols + ["COLLFEE"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print(df[cutoff_cols + ["COLLFEE"]].dtypes)

OC_BOYS         float64
OC_GIRLS        float64
SC_BOYS         float64
SC_GIRLS        float64
ST_BOYS         float64
ST_GIRLS        float64
BCA_BOYS        float64
BCA_GIRLS       float64
BCB_BOYS        float64
BCB_GIRLS       float64
BCC_BOYS        float64
BCC_GIRLS       float64
BCD_BOYS        float64
BCD_GIRLS       float64
BCE_BOYS        float64
BCE_GIRLS       float64
OC_EWS_BOYS     float64
OC_EWS_GIRLS    float64
COLLFEE         float64
dtype: object

In [42]:
print("Total missing values:", df.isna().sum().sum())

Total missing values: 2754

In [43]:
print(df[["INSTCODE", "NAME OF THE INSTITUTION", "branch_code"]].head(20))

   INSTCODE                            NAME OF THE INSTITUTION branch_code
0      ACEE                      ADARSH COLLEGE OF ENGINEERING         CIV
1      ACEE                      ADARSH COLLEGE OF ENGINEERING         CSE
2      ACEE                      ADARSH COLLEGE OF ENGINEERING         ECE
3      ACEE                      ADARSH COLLEGE OF ENGINEERING         EEE
4      ACEE                      ADARSH COLLEGE OF ENGINEERING         MEC
5      ACET       ADITYA COLLEGE OF ENGINEERING AND TECHNOLOGY         CIV
6      ACET       ADITYA COLLEGE OF ENGINEERING AND TECHNOLOGY         CSD
7      ACET       ADITYA COLLEGE OF ENGINEERING AND TECHNOLOGY         CSE
8      ACET       ADITYA COLLEGE OF ENGINEERING AND TECHNOLOGY         CSM
9      ACET       ADITYA COLLEGE OF ENGINEERING AND TECHNOLOGY         ECE
10     ACET       ADITYA COLLEGE OF ENGINEERING AND TECHNOLOGY         EEE
11     ACET       ADITYA COLLEGE OF ENGINEERING AND TECHNOLOGY         INF
12     ACET       ADITYA COLLEGE OF ENGINEERING AND TECHNOLOGY         MEC
13     ACPS                         ADITYA COLLEGE OF PHARMACY         PHD
14   ANURSF  ADI KAVI NANNAYA UNIVERSITY COLLEGE OF ENGG.-S...         CIV
15   ANURSF  ADI KAVI NANNAYA UNIVERSITY COLLEGE OF ENGG.-S...         CSE
16   ANURSF  ADI KAVI NANNAYA UNIVERSITY COLLEGE OF ENGG.-S...         ECE
17   ANURSF  ADI KAVI NANNAYA UNIVERSITY COLLEGE OF ENGG.-S...         EIE
18   ANURSF  ADI KAVI NANNAYA UNIVERSITY COLLEGE OF ENGG.-S...         MEC
19     APCS                            ADITYA PHARMACY COLLEGE         PHD

In [44]:
print(
    df.groupby("branch_code")["OC_EWS_BOYS"]
      .apply(lambda x: x.isna().sum())
      .sort_values(ascending=False)
)

branch_code
MEC    82
CIV    79
ECE    68
EEE    66
CSE    57
       ..
ECM     0
MET     0
NAM     0
PEE     0
RBT     0
Name: OC_EWS_BOYS, Length: 69, dtype: int64

In [46]:
missing_by_branch = df.groupby("branch_code")["OC_EWS_BOYS"].agg(
    total="size",
    missing=lambda x: x.isna().sum()
)

missing_by_branch["missing_pct"] = (
    missing_by_branch["missing"] / missing_by_branch["total"] * 100
)

print(missing_by_branch.sort_values("missing_pct", ascending=False))

             total  missing  missing_pct
branch_code
CN               2        2        100.0
CDA              2        2        100.0
CBC              2        2        100.0
BDT              2        2        100.0
AUT              3        3        100.0
...            ...      ...          ...
ECM              1        0          0.0
MET              2        0          0.0
NAM              1        0          0.0
PEE              1        0          0.0
RBT              1        0          0.0

[69 rows x 3 columns]

In [47]:
print(
    df.groupby(df["OC_EWS_BOYS"].isna())[
        ["OC_BOYS", "SC_BOYS", "ST_BOYS", "BCA_BOYS", "BCB_BOYS"]
    ].count()
)

             OC_BOYS  SC_BOYS  ST_BOYS  BCA_BOYS  BCB_BOYS
OC_EWS_BOYS
False            954      994      989       990       988
True             410      449      430       437       433

In [48]:
fee_missing = df[df["COLLFEE"].isna()]

print(fee_missing[["INSTCODE", "NAME OF THE INSTITUTION", "branch_code"]].head(20))

     INSTCODE                          NAME OF THE INSTITUTION branch_code
1383   BESTPU  BHARATIYA ENGG SCI. &TECH INNOVATION UNIVERSITY          AI
1385   BESTPU  BHARATIYA ENGG SCI. &TECH INNOVATION UNIVERSITY          CS
1387   BESTPU  BHARATIYA ENGG SCI. &TECH INNOVATION UNIVERSITY         CSE
1389   BESTPU  BHARATIYA ENGG SCI. &TECH INNOVATION UNIVERSITY          DS
1392   APUCPU                                APOLLO UNIVERSITY         CAD
1394   APUCPU                                APOLLO UNIVERSITY         CSC
1396   APUCPU                                APOLLO UNIVERSITY         CSE
1398   APUCPU                                APOLLO UNIVERSITY         CSM
1400     CVST                 SVVU COLLEGE OF DAIRY TECHNOLOGY         BDT
1402   MBUTPU                            MOHAN BABU UNIVERSITY         CIV
1404   MBUTPU                            MOHAN BABU UNIVERSITY         CSC
1406   MBUTPU                            MOHAN BABU UNIVERSITY         CSD
1408   MBUTPU                            MOHAN BABU UNIVERSITY         CSE
1410   MBUTPU                            MOHAN BABU UNIVERSITY         CSM
1412   MBUTPU                            MOHAN BABU UNIVERSITY         ECE
1414   MBUTPU                            MOHAN BABU UNIVERSITY         EEE
1416   MBUTPU                            MOHAN BABU UNIVERSITY         EIE
1418   MBUTPU                            MOHAN BABU UNIVERSITY         INF
1420   MBUTPU                            MOHAN BABU UNIVERSITY         MEC
1422   SPMUSF       SCHOOL OF ENGG. TECH. SPMVV - SELF FINANCE         CSE

In [49]:
fee_check = df.groupby("INSTCODE")["COLLFEE"].agg(
    total="size",
    missing=lambda x: x.isna().sum(),
    unique_fees=lambda x: x.dropna().nunique()
)

print(fee_check[fee_check["missing"] > 0])

          total  missing  unique_fees
INSTCODE
ADTPPU       22       11            1
AITSPU       22       11            1
APUCPU        8        4            1
BESTPU        8        4            1
CENUPU       25       12            1
CVST          2        1            1
GGURPU       22       11            1
MBUTPU       20       10            1
SPMUSF        8        4            1
SRMUPU       10        5            1
VITAPU       26       13            1
VITAPUMT      4        2            1
YSRA          2        1            1

In [52]:
df["COLLFEE"] = df.groupby("INSTCODE")["COLLFEE"].transform(
    lambda x: x.fillna(x.median())
)
print("Missing COLLFEE:", df["COLLFEE"].isna().sum())

Missing COLLFEE: 0

In [53]:
print("Total missing values:", df.isna().sum().sum())

Total missing values: 2665

In [54]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [55]:
print("Duplicate college-branch rows:",
      df.duplicated(subset=["INSTCODE", "branch_code"]).sum())

Duplicate college-branch rows: 89

In [58]:
print(
    "Duplicate college-branch-region rows:",
    df.duplicated(
        subset=["INSTCODE", "branch_code", "A_REG"]
    ).sum()
)

Duplicate college-branch-region rows: 0

In [59]:
print("Negative cutoff values:")
print((df[cutoff_cols] < 0).sum().sum())

print("Negative fees:")
print((df["COLLFEE"] < 0).sum())

print("Zero fees:")
print((df["COLLFEE"] == 0).sum())

Negative cutoff values:
0
Negative fees:
0
Zero fees:
0

In [60]:
print(df[cutoff_cols].min())
print("\nMaximum:")
print(df[cutoff_cols].max())

OC_BOYS         2039.0
OC_GIRLS        2074.0
SC_BOYS         3628.0
SC_GIRLS        3628.0
ST_BOYS         3414.0
ST_GIRLS        5068.0
BCA_BOYS        2039.0
BCA_GIRLS       2074.0
BCB_BOYS        2039.0
BCB_GIRLS       2074.0
BCC_BOYS        2039.0
BCC_GIRLS       2074.0
BCD_BOYS        2039.0
BCD_GIRLS       2074.0
BCE_BOYS        2039.0
BCE_GIRLS       2544.0
OC_EWS_BOYS     1682.0
OC_EWS_GIRLS    1572.0
dtype: float64

Maximum:
OC_BOYS         177810.0
OC_GIRLS        177810.0
SC_BOYS         177872.0
SC_GIRLS        177872.0
ST_BOYS         177865.0
ST_GIRLS        177877.0
BCA_BOYS        177810.0
BCA_GIRLS       177810.0
BCB_BOYS        177845.0
BCB_GIRLS       177845.0
BCC_BOYS        177810.0
BCC_GIRLS       177810.0
BCD_BOYS        177810.0
BCD_GIRLS       177810.0
BCE_BOYS        177810.0
BCE_GIRLS       177810.0
OC_EWS_BOYS     177081.0
OC_EWS_GIRLS    176510.0
dtype: float64

In [61]:
id_cols = [
    "INSTCODE",
    "NAME OF THE INSTITUTION",
    "TYPE",
    "INST_REG",
    "DIST",
    "PLACE",
    "COED",
    "AFFL.",
    "ESTD",
    "A_REG",
    "branch_code",
    "COLLFEE"
]

df_long = df.melt(
    id_vars=id_cols,
    value_vars=cutoff_cols,
    var_name="Category_Gender",
    value_name="Cutoff"
)

print(df_long.shape)
print(df_long.head())

(28170, 14)
  INSTCODE        NAME OF THE INSTITUTION TYPE INST_REG DIST       PLACE  \
0     ACEE  ADARSH COLLEGE OF ENGINEERING  PVT       AU   EG  GOLLAPROLU
1     ACEE  ADARSH COLLEGE OF ENGINEERING  PVT       AU   EG  GOLLAPROLU
2     ACEE  ADARSH COLLEGE OF ENGINEERING  PVT       AU   EG  GOLLAPROLU
3     ACEE  ADARSH COLLEGE OF ENGINEERING  PVT       AU   EG  GOLLAPROLU
4     ACEE  ADARSH COLLEGE OF ENGINEERING  PVT       AU   EG  GOLLAPROLU

   COED  AFFL.    ESTD A_REG branch_code  COLLFEE Category_Gender    Cutoff
0  COED  JNTUK  2008.0    AU         CIV  43000.0         OC_BOYS  146103.0
1  COED  JNTUK  2008.0    AU         CSE  43000.0         OC_BOYS  128861.0
2  COED  JNTUK  2008.0    AU         ECE  43000.0         OC_BOYS  161894.0
3  COED  JNTUK  2008.0    AU         EEE  43000.0         OC_BOYS       NaN
4  COED  JNTUK  2008.0    AU         MEC  43000.0         OC_BOYS  152545.0

In [63]:
print(df_long["Category_Gender"].unique())

['OC_BOYS' 'OC_GIRLS' 'SC_BOYS' 'SC_GIRLS' 'ST_BOYS' 'ST_GIRLS' 'BCA_BOYS'
 'BCA_GIRLS' 'BCB_BOYS' 'BCB_GIRLS' 'BCC_BOYS' 'BCC_GIRLS' 'BCD_BOYS'
 'BCD_GIRLS' 'BCE_BOYS' 'BCE_GIRLS' 'OC_EWS_BOYS' 'OC_EWS_GIRLS']

In [64]:
df_long[["Category", "Gender"]] = df_long["Category_Gender"].str.rsplit(
    "_", n=1, expand=True
)

print(df_long[["Category_Gender", "Category", "Gender"]].drop_duplicates())

      Category_Gender Category Gender
0             OC_BOYS       OC   BOYS
1565         OC_GIRLS       OC  GIRLS
3130          SC_BOYS       SC   BOYS
4695         SC_GIRLS       SC  GIRLS
6260          ST_BOYS       ST   BOYS
7825         ST_GIRLS       ST  GIRLS
9390         BCA_BOYS      BCA   BOYS
10955       BCA_GIRLS      BCA  GIRLS
12520        BCB_BOYS      BCB   BOYS
14085       BCB_GIRLS      BCB  GIRLS
15650        BCC_BOYS      BCC   BOYS
17215       BCC_GIRLS      BCC  GIRLS
18780        BCD_BOYS      BCD   BOYS
20345       BCD_GIRLS      BCD  GIRLS
21910        BCE_BOYS      BCE   BOYS
23475       BCE_GIRLS      BCE  GIRLS
25040     OC_EWS_BOYS   OC_EWS   BOYS
26605    OC_EWS_GIRLS   OC_EWS  GIRLS

In [65]:
df_long = df_long.dropna(subset=["Cutoff"]).reset_index(drop=True)

print("Shape:", df_long.shape)
print("Missing Cutoff:", df_long["Cutoff"].isna().sum())

Shape: (25505, 16)
Missing Cutoff: 0

In [66]:
print(df_long.columns.tolist())
print()
print(df_long[[
    "INSTCODE",
    "branch_code",
    "A_REG",
    "Category",
    "Gender",
    "Cutoff",
    "COLLFEE"
]].head(10))

['INSTCODE', 'NAME OF THE INSTITUTION', 'TYPE', 'INST_REG', 'DIST', 'PLACE', 'COED', 'AFFL.', 'ESTD', 'A_REG', 'branch_code', 'COLLFEE', 'Category_Gender', 'Cutoff', 'Category', 'Gender']

  INSTCODE branch_code A_REG Category Gender    Cutoff  COLLFEE
0     ACEE         CIV    AU       OC   BOYS  146103.0  43000.0
1     ACEE         CSE    AU       OC   BOYS  128861.0  43000.0
2     ACEE         ECE    AU       OC   BOYS  161894.0  43000.0
3     ACEE         MEC    AU       OC   BOYS  152545.0  43000.0
4     ACET         CIV    AU       OC   BOYS   71458.0  53500.0
5     ACET         CSD    AU       OC   BOYS   38871.0  53500.0
6     ACET         CSE    AU       OC   BOYS   25298.0  53500.0
7     ACET         CSM    AU       OC   BOYS   32023.0  53500.0
8     ACET         ECE    AU       OC   BOYS   42426.0  53500.0
9     ACET         EEE    AU       OC   BOYS   49158.0  53500.0

In [67]:
df_long = df_long.drop(columns=["Category_Gender"])

print(df_long.shape)
print(df_long.columns.tolist())

(25505, 15)
['INSTCODE', 'NAME OF THE INSTITUTION', 'TYPE', 'INST_REG', 'DIST', 'PLACE', 'COED', 'AFFL.', 'ESTD', 'A_REG', 'branch_code', 'COLLFEE', 'Cutoff', 'Category', 'Gender']

In [68]:
missing = df_long.isna().sum()

print(missing[missing > 0])
print("\nTotal missing values:", df_long.isna().sum().sum())

Series([], dtype: int64)

Total missing values: 0